/**
 * Created by lmy on 17-5-3.
 */
$(document).ready(function(){
    $("#questionOne").click(function(){
        $("#panelOne").slideToggle("slow");
    });
    $("#questionTow").click(function(){
        $("#panelTow").slideToggle("slow");
    });
    $("#questionThree").click(function(){
        $("#panelThree").slideToggle("slow");
    });
    $("#questionFour").click(function(){
        $("#panelFour").slideToggle("slow");
    });
    $("#questionFive").click(function(){
        $("#panelFive").slideToggle("slow");
    });
});